export const CONTROL_DEFAULTS = {
  scene: {
    background: '#ffffff',
    meshCount: 5,
    gap: 4.2,
    groupY: 0,
  },
  geometry: {
    width: 4.35,
    height: 2.95,
    widthBias: 1,
    varySizes: false,
    widthVariation: 0.28,
    heightVariation: 0.2,
    variationSeed: 11,
    segmentsX: 100,
    segmentsY: 100,
  },
  scroll: {
    sensitivity: 1000,
    stiffness: 140,
    damping: 24,
    mass: 1,
    maxVelocity: 8,
    mouseMultiplier: 1,
    touchMultiplier: 1.6,
    firefoxMultiplier: 45,
  },
  material: {
    wireframe: false,
  },
  trig: {
    progressMultiplier: -0.74,
    sphereRadiusMultiplier: 3.9,
    sphereCenterY: -0.2,
    bendStrength: -2.3,
  },
  fragment: {
    enableMask: false,
    maskStart: -0.7,
    maskEnd: 0,
  },
  interaction: {
    enableClickToggle: true,
    toggleShiftX: -3.5,
    requireFlatForShift: true,
    flatAngleThreshold: 0.09,
    centerWindow: 0.35,
    toggleResponse: 6,
    visibilityResponse: 6,
    hitPaddingX: 0.7,
    hitPaddingY: 0.5,
    hitPlaneZ: 0.08,
    slideFadeMinOpacity: 0.85,
    slideFadeExponent: 1.35,
  },
  cameraControls: {
    orientation: 'vertical',
    posX: 0,
    posY: 0,
    posZ: 5,
    lookAtX: 0,
    lookAtY: 0,
    lookAtZ: 0,
    roll: 0,
    fov: 70,
    zoom: 1,
    near: 0.1,
    far: 1000,
    focus: 10,
  },
}
