export const CONTROL_DEFAULTS = {
  scene: {
    background: '#000000',
    meshCount: 5,
    gap: 4.2,
    groupY: 0,
  },
  geometry: {
    width: 5.9,
    height: 4.5,
    widthBias: 1.3,
    varySizes: false,
    widthVariation: 0.28,
    heightVariation: 0.2,
    variationSeed: 11,
    segmentsX: 100,
    segmentsY: 100,
  },
  scroll: {
    sensitivity: 1350,
    stiffness: 140,
    damping: 24,
    mass: 1,
    maxVelocity: 8,
    mouseMultiplier: 1,
    touchMultiplier: 1.6,
    firefoxMultiplier: 45,
  },
  material: {
    wireframe: false,
  },
  trig: {
    progressMultiplier: -1.1,
    sphereRadiusMultiplier: 4.1,
    sphereCenterY: 2.0,
    bendStrength: -1.2,
  },
  fragment: {
    enableMask: false,
    maskStart: -0.7,
    maskEnd: 0,
  },
  interaction: {
    enableClickToggle: true,
    toggleShiftX: -3.5,
    requireFlatForShift: true,
    flatAngleThreshold: 0.09,
    centerWindow: 0.35,
    toggleResponse: 6,
    visibilityResponse: 6,
    hitPaddingX: 0.7,
    hitPaddingY: 0.5,
    hitPlaneZ: 0.08,
    slideFadeMinOpacity: 0.85,
    slideFadeExponent: 1.35,
  },
  cameraControls: {
    orientation: 'vertical',
    posX: 0,
    posY: 0,
    posZ: 7.3,
    lookAtX: 0,
    lookAtY: 0.09,
    lookAtZ: 0,
    roll: 0,
    fov: 90,
    zoom: 1.53,
    near: 0.1,
    far: 1000,
    focus: 10,
  },
  titles: {
    enabled: true,
    fontSize: 0.4,
    gap: 4.2,
    groupY: 2.5,
    color: '#000000',
  },
}
